spring:
  application:
    name: phone-booking-app
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    pool:
      enabled: true
    properties:
      schema: ${PHONE_BOOKING_SCHEMA:phone_booking}
      sslMode: DISABLE

  liquibase:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}?sslmode=DISABLE
    user: postgres
    password: postgres
    default-schema: phone_booking
    contexts: production

  lifecycle:
    timeout-per-shutdown-phase: 5m

server:
  port: 8080
  shutdown: graceful

logging:
#  config: classpath:log4j2.yml
  level:
    root: DEBUG
    org.fan.phonebooking: DEBUG
    liquibase: INFO
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgressql.PARAM: DEBUG