version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgress_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /opt/postgres
    volumes:
      - ${POSTGRES_PATH:-./db/postgres}:/opt/postgres
      - ./Docker/init.sql:/docker-entypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
